### ISSUE TITLE
[질문]공백 포함 입력받기

### ISSUE THREAD

**Issue by nick11967** [22S-LGN-PS/programming-challenges#19]
관련 문제: 10152 Shoemaker's Problem
C++ 에서 string 변수에 공백을 포함하여 문자열을 입력받고자 했습니다.
입력 받을 문자열의 수 n을 정수로 입력 받고 getline(cin, turtle); 로 한 줄을 입력 받았는데 이러면 앞서 정수 입력 후 enter를 입력한 것 때문인지 빈 문자열이 한 번 입력 됩니다. 이 문제에서는 vertor에 저장할 때 0번 방을 무시하고 1번 방부터 저장된 값을 사용했는데 앞서 나온 공백을 무시하려면 어떻게 해야 할까요?

**Comment by lucetre** [comment]
You can check this link
https://stackoverflow.com/a/10553849
