### ISSUE TITLE
expressions book solution

### ISSUE THREAD

**Issue by lucetre** [22S-LGN-PS/programming-challenges#35]
![image](https://user-images.githubusercontent.com/26702243/185781086-8660a6a5-53b6-4db0-8244-32be6003ebc9.png)
![image](https://user-images.githubusercontent.com/26702243/185781088-db824650-0cd5-41c1-a534-7aa865c23e9f.png)
![image](https://user-images.githubusercontent.com/26702243/185781093-a3028f5d-7fc3-4394-b9da-d851793bb995.png)
![image](https://user-images.githubusercontent.com/26702243/185781096-e92f2e24-8215-4137-a118-7db697bb89f6.png)

**Comment by nick11967** [comment]
main code

![main](https://user-images.githubusercontent.com/96417461/187169294-b0123a78-ea26-46e1-b4c7-f212ca2f1e4f.jpg)

**Comment by nick11967** [comment]
이 코드는 expression의 길이가 홀수일 때를 고려하지 않습니다!
입력을 받은 후에 홀수인지 판별하는 조건을 넣어주면 올바른 답을 출력합니다.
